const lang = {
    en: {
        search: "Search",
        gptSearchPlaceholder: "What would you like to watch today",
        mainPageHeading: "Unlimited movies, TV shows and more",
        text_1: "Watch anywhere. Cancel anytime.",
        text_2: "Ready to watch? Enter your email to create or restart your membership.",
        email: "Email address",
        getstarted: "Get started",
        signin: "Sign In",
        signup: "Sign Up",
        signInPageHeading: "Sign In",
        emailOrMobile: "Email or mobile number",
        password: "Password",
        signInButton: "Sign In",
        or: "OR",
        useSignInCode: "Use a sign-in code",
        forgotPassword: "Forgot password?",
        rememberMe: "Remember me",
        newToNetflix: "New to Netflix? Sign up now",
        reCAPTCHAProtection: "This page is protected by Google reCAPTCHA to ensure you're not a bot.",
        learnMore: "Learn more",
        enterValidEmailOrPhone: "Please enter a valid email address or phone number.",
        passwordRequirement: "Your password must contain uppercase, lowercase letters & numbers.",
        enterFullName: "Enter your full name",
        alreadyAUser: "Already a user?",
        accountCreated: "Account created successfully",
        enterFullName: "Enter your full name",
        fullName: "Full name",
        emailInUse: "Email already in use",
        invalidCredentials: "Invalid credentials"
    },
    hn: {
        search: "खोज",
        gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
        mainPageHeading: "असीमित फिल्में, टीवी शो और बहुत कुछ",
        text_1: "कहीं भी देखो. किसी भी समय रद्द करें.",
        text_2: "देखने के लिए तैयार हैं? अपनी सदस्यता बनाने या पुनः आरंभ करने के लिए अपना ईमेल दर्ज करें।",
        email: "मेल पता",
        getstarted: "शुरू हो जाओ",
        signin: "साइन इन करें",
        signup: "साइन अप करें",
        signInPageHeading: "साइन इन करें",
        emailOrMobile: "ईमेल या मोबाइल नंबर",
        password: "पासवर्ड",
        signInButton: "साइन इन करें",
        or: "या",
        useSignInCode: "साइन-इन कोड का उपयोग करें",
        forgotPassword: "पासवर्ड भूल गए?",
        rememberMe: "मुझे याद रखें",
        newToNetflix: "Netflix पर नए हैं? अभी साइन अप करें",
        reCAPTCHAProtection: "यह पृष्ठ Google reCAPTCHA द्वारा सुरक्षित है ताकि यह सुनिश्चित किया जा सके कि आप रोबोट नहीं हैं।",
        learnMore: "अधिक जानें",
        enterValidEmailOrPhone: "कृपया एक वैध ईमेल पता या फोन नंबर दर्ज करें।",
        passwordRequirement: "आपके पासवर्ड में बड़े, छोटे अक्षर और संख्याएँ होनी चाहिए।",
        enterFullName: "अपना पूरा नाम दर्ज करें",
        alreadyAUser: "पहले से ही एक उपयोगकर्ता?",
        accountCreated: "खाता सफलतापूर्वक बनाया गया",
        enterFullName: "अपना पूरा नाम दर्ज करें",
        fullName: "पूरा नाम",
        emailInUse: "ईमेल पहले से ही उपयोग में है",
        invalidCredentials: "अमान्य क्रेडेंशियल्स"

    },
}



export default lang;